name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: build
        run: |
          - chmod +x build.sh
          - ./build.sh

      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            - ./rusty-shiba-db-linux-arm64
            - ./rusty-shiba-db-linux-amd64
            - ./rusty-shiba-db-darwin-arm64
            - ./rusty-shiba-db-darwin-amd64
            - ./rusty-shiba-db-windows-arm64.exe
            - ./rusty-shiba-db-windows-amd64.exe
          tag_name: ${{ steps.tag.tag }}
          generate_release_notes: 'true'
          draft: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}