name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.1.0
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: ''
          name: 'rusty-shiba-db'
          compress: 'true'
          dest: 'dist'

      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/rusty-shiba-db-linux-amd64.tar.gz
            ./dist/rusty-shiba-db-darwin-amd64.tar.gz
            ./dist/rusty-shiba-db-windows-amd64.tar.gz
          tag_name: ${{ steps.tag.tag }}
          generate_release_notes: 'true'
          draft: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}