name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GIN_MODE: release
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...

      - name: Permissionms
        run: sudo mkdir /data/rsdb/ && sudo chmod -R 777 /data/

      - name: Test
        run: go test -v ./... -coverprofile=./cov.out -json > test-report.out

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
